spring:
  application:
    name: spring

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:benchmark}
    username: ${DB_USER:benchmark}
    password: ${DB_PASSWORD:benchmark}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  sql:
    init:
      mode: always

  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
